### ISSUE TITLE
Random generation error

### ISSUE THREAD

**Issue by bpatrik** [axelpale/poisson-process#1]
Hi

I've tested the random generation of your code. I've generated more than 1000 samples. While the mean of them was correct, the variance not. 
The same algorith is also discussed here:
http://preshing.com/20111007/how-to-generate-random-timings-for-a-poisson-process/
The last comment shows the same issue. 

I've implemented a working random generator based on [wikipedia](https://en.wikipedia.org/wiki/Poisson_distribution), you can find it here:
https://gist.github.com/bpatrik/05504ca54d015d195282a55d9e74f6f7

**Comment by axelpale** [comment]
Hi. Awesome, this is very valuable feedback!

I will look into this as soon as I have time. Meanwhile, could you be able to share your test code, for example as a gist? I could use it as a starting point of a unit test suite for the lib. Thanks!

**Comment by bpatrik** [comment]
Hi,
Thank you quick reply!

Here the code that I used for testing:
https://gist.github.com/bpatrik/13dca0f52c3320dcae7aadd232b39249
I'm testing 3 algorithms, including yours. Results are printed to the console.

I also used [wolfamAplha](https://www.wolframalpha.com/input/?i=poission+distribution+100) to check my results.

**Comment by axelpale** [comment]
Hello,
I finally had time to think this through. Whew, this was not a simple matter but I think the results are good :)

I found couple of issues from your tests and I also wrote comprehensive tests for PoissonProcess. I managed to proof that PoissonProcess.sample truly samples from exponential distribution and that this leads to a Poisson distributed chain of events, as planned. Therefore I put into question if your test the right thing. If you would like to run my tests, see readme for instructions.

What do you think about these notions about your tests:

- You test if mean and variance match. Yes, they should be equal in Poisson distribution but now we are dealing with an exponential distribution instead. You know, interarrival times in a Poisson process are exponentially distributed. The PoissonProcess.sample generates those interarrivals. With exponential distributions the variance = mean^2, and that goes well with the results mentioned by Flavien in http://preshing.com/20111007/how-to-generate-random-timings-for-a-poisson-process/
- For variance, you use biased sample variance. Unbiased variance (divided by n - 1 instead of n) gives a little higher and thus more correct results. This is understandable because there tend to be more extreme values in the population than in the sample in general.

**Comment by bpatrik** [comment]
Hi,

Thank you for thinking this through.
I checked your lib again and I can not reproduce the error.
I find it strange, since I remember having some errors, especially with high expected values.
Probably it was because of the mentioned error in my tests.
